dfWeightedDensity <- data.frame(state=c("New York"), density=c(28161.5), stringsAsFactors=FALSE)
dfWeightedDensity <- rbind(dfWeightedDensity,list("Hawaii", 8479.7),
      list("California", 8213.0))
dfWeightedDensity <- rbind(dfWeightedDensity,list("New Jersey", 7940.6))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Illinois", 6660.8))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Massachusetts", 6585.6))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Nevada", 5419.5))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Rhode Island", 5034.0))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Pennsylvania", 4886.8))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Maryland", 4555.0))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Florida", 3750.6))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Connecticut", 3583.0))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Arizona", 3582.5))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Colorado", 3500.0))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Utah", 3429.9))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Washington", 3344.8))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Virginia", 3249.6))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Texas", 3138.6))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Oregon", 3113.8))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Delaware", 2643.5))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Wisconsin", 2598.5))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Michigan", 2527.3))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Minnesota", 2416.5))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Ohio", 2388.8))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Nebraska", 2285.2))
dfWeightedDensity <- rbind(dfWeightedDensity,list("New Mexico", 2108.8))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Louisiana", 1931.2))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Missouri", 1895.7))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Alaska", 1834.1))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Kansas", 1772.6))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Indiana", 1740.0))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Oklahoma", 1602.3))
dfWeightedDensity <- rbind(dfWeightedDensity,list("North Dakota", 1569.1))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Georgia", 1550.9))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Idaho", 1488.8))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Kentucky", 1464.2))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Iowa", 1463.1))
dfWeightedDensity <- rbind(dfWeightedDensity,list("New Hampshire", 1320.9))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Tennessee", 1288.4))
dfWeightedDensity <- rbind(dfWeightedDensity,list("North Carolina", 1181.9))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Montana", 1088.3))
dfWeightedDensity <- rbind(dfWeightedDensity,list("South Dakota", 1045.9))
dfWeightedDensity <- rbind(dfWeightedDensity,list("South Carolina", 1018.7))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Wyoming", 998.5))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Vermont", 947.2))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Alabama", 942.2))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Maine", 881.7))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Arkansas", 807.9))
dfWeightedDensity <- rbind(dfWeightedDensity,list("West Virginia", 792.1))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Mississippi", 694.9))

#Europe

dfWeightedDensityEurope <- data.frame(country=c("Spain"), density=c(737), stringsAsFactors=FALSE)
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Netherlands", 546),
                           list("California", 8213.0))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("England", 531))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Italy", 453))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Belgium", 434))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Switzerland", 385))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Greece", 379))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Germany", 376))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Portugal", 255))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Czech Republic", 236))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Austria", 220))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Wales", 204))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Scotland", 200))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Poland", 196))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("France", 195))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Iceland", 187))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Denmark", 183))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Northern Ireland", 160))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Norway", 89))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Sweden", 84))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Ireland", 81))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Poland", 196))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Finland", 53))
