# These numbers are based on the U.S. Cnesus Bureau's formula
# https://www.census.gov/prod/cen2010/reports/c2010sr-01.pdf
# Sources: https://skyscraperpage.com/forum/showthread.php?t=211827
#          https://ggwash.org/view/68144/this-is-a-better-way-to-look-at-how-built-up-our-region-is

dfWeightedDensity <- data.frame(state=c("New York"), density=c(28161.5), stringsAsFactors=FALSE)
dfWeightedDensity <- rbind(dfWeightedDensity,list("Hawaii", 8479.7),
      list("California", 8213.0))
dfWeightedDensity <- rbind(dfWeightedDensity,list("New Jersey", 7940.6))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Illinois", 6660.8))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Massachusetts", 6585.6))
dfWeightedDensity <- rbind(dfWeightedDensity,list("District of Columbia", 6388))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Nevada", 5419.5))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Rhode Island", 5034.0))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Pennsylvania", 4886.8))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Maryland", 4555.0))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Florida", 3750.6))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Connecticut", 3583.0))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Arizona", 3582.5))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Colorado", 3500.0))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Utah", 3429.9))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Washington", 3344.8))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Virginia", 3249.6))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Texas", 3138.6))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Oregon", 3113.8))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Delaware", 2643.5))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Wisconsin", 2598.5))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Michigan", 2527.3))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Minnesota", 2416.5))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Ohio", 2388.8))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Nebraska", 2285.2))
dfWeightedDensity <- rbind(dfWeightedDensity,list("New Mexico", 2108.8))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Louisiana", 1931.2))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Missouri", 1895.7))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Alaska", 1834.1))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Kansas", 1772.6))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Indiana", 1740.0))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Oklahoma", 1602.3))
dfWeightedDensity <- rbind(dfWeightedDensity,list("North Dakota", 1569.1))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Georgia", 1550.9))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Idaho", 1488.8))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Kentucky", 1464.2))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Iowa", 1463.1))
dfWeightedDensity <- rbind(dfWeightedDensity,list("New Hampshire", 1320.9))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Tennessee", 1288.4))
dfWeightedDensity <- rbind(dfWeightedDensity,list("North Carolina", 1181.9))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Montana", 1088.3))
dfWeightedDensity <- rbind(dfWeightedDensity,list("South Dakota", 1045.9))
dfWeightedDensity <- rbind(dfWeightedDensity,list("South Carolina", 1018.7))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Wyoming", 998.5))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Vermont", 947.2))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Alabama", 942.2))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Maine", 881.7))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Arkansas", 807.9))
dfWeightedDensity <- rbind(dfWeightedDensity,list("West Virginia", 792.1))
dfWeightedDensity <- rbind(dfWeightedDensity,list("Mississippi", 694.9))

# Europe numbers from 
# https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/LUISA/SecondaryOutput_Indicators/Europe/REF-2016/UDP/PWD/
# people per km^2
dfWeightedDensityEuro <- data.frame(country=c("Austria"), density=c(4058), stringsAsFactors=FALSE)
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Belgium", 2852))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Bulgaria", 3580))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Cyprus", 2146))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Czech Republic", 2090))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Germany", 2466))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Denmark", 2401))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Estonia", 2355))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Greece", 8410))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Spain", 11522))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Finland", 1691))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("France", 4512))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Croatia", 1363))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Hungary", 2532))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Ireland", 2370))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Italy", 3611))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Lithuania", 1807))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Luxembourg", 1886))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Latvia", 2507))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Malta", 4159))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Netherlands", 4071))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Poland", 2513))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Portugal", 3526))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Romania", 4044))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Sweden", 2587))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Slovenia", 1986))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("Slovakia", 2327))
dfWeightedDensityEuro <- rbind(dfWeightedDensityEuro, list("United Kingdom", 3587))

#Europe numbers similar to Antweiler's (see below)
dfWeightedDensityEurope <- data.frame(country=c("Spain"), density=c(737), stringsAsFactors=FALSE)
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Netherlands", 546),
                           list("California", 8213.0))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("England", 531))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Italy", 453))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Belgium", 434))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Switzerland", 385))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Greece", 379))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Germany", 376))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Portugal", 255))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Czech Republic", 236))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Austria", 220))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Wales", 204))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Scotland", 200))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Poland", 196))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("France", 195))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Iceland", 187))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Denmark", 183))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Northern Ireland", 160))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Norway", 89))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Sweden", 84))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Ireland", 81))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Poland", 196))
dfWeightedDensityEurope <- rbind(dfWeightedDensity,list("Finland", 53))


# Another data set from https://wernerantweiler.ca/blog.php?item=2020-04-12
# Thanks to DanSpartan on Unstuck Politics for the pointer
# This one should be better, and uses similar calculations to the European set
# On second thought, there is no unit for this calculation, and MA and NV are separated by
# a factor of 8, while with the Census method, they are close.

dfWeightedDensityAntweiler <- data.frame(state=c("Alabama"), density=c(64.194), population=c(4.903), stringsAsFactors=FALSE)
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Alaska", 5.625, 0.732))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Arizona", 76.011, 7.279))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Arkansas", 40.781, 3.018))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("California", 329.123, 39.512))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Colorado", 121.156, 5.759))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Connecticut", 371.439, 3.565))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Delaware", 259.754, 0.974))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Florida", 286.392, 21.478))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Georgia", 204.405, 10.617))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Hawaii", 250.577, 1.416))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Idaho", 35.138, 1.787))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Illinois", 410.564, 12.672))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Indiana", 138.052, 6.732))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Iowa", 43.676, 3.155))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Kansas", 64.891, 2.913))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Kentucky", 91.305, 4.468))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Louisiana", 97.165, 4.649))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Maine", 37.415, 1.344))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Maryland", 453.378, 6.046))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Massachusetts", 552.354, 6.893))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Michigan", 201.263, 9.987))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Minnesota", 128.880, 5.640))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Mississippi", 37.282, 2.976))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Missouri", 113.870, 6.137))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Montana", 6.875, 1.069))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Nebraska", 70.961, 1.934))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Nevada", 64.351, 3.080))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("New Hampshire", 95.416, 1.360))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("New Jersey", 785.426, 8.882))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("New Mexico", 24.910, 2.097))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("New York", 1322.99, 19.454))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("North Carolina", 150.632, 10.488))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("North Dakota", 9.608, 0.762))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Ohio", 228.178, 11.689))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Oklahoma", 73.170, 3.957))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Oregon", 76.903, 4.218))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Pennsylvania", 275.998, 12.802))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Rhode Island", 455.294, 1.059))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("South Carolina", 97.514, 5.149))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("South Dakota", 12.533, 0.885))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Tennessee", 123.679, 6.829))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Texas", 245.431, 28.996))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Utah", 135.237, 3.206))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Vermont", 34.090, 0.624))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Virginia", 286.827, 8.536))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Washington", 129.547, 7.615))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("West Virginia", 44.760, 1.792))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Wisconsin", 112.485, 5.822))
dfWeightedDensityAntweiler <- rbind(dfWeightedDensityAntweiler, list("Wyoming", 3.270, 0.579))

# Population numbers from Antweiler, D.C. population from Wikipedia - 2018 Census estimate
dfStatePop <- read.csv(here("code/covid19/density/USStatePopulation.csv"))